# Generated by Django 5.1.6 on 2025-03-28 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gantttask',
            name='gantt_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_tasks', to='boards.ganttboard'),
        ),
        migrations.AddField(
            model_name='kanbanboard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_boards', to='projects.project'),
        ),
        migrations.AddField(
            model_name='kanbancolumn',
            name='kanban_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='boards.kanbanboard'),
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='kanban_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_tasks', to='boards.kanbancolumn'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskboard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_boards', to='projects.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.taskboard'),
        ),
    ]
